# Generated by Django 3.1.7 on 2021-04-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_category_catedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
