# Generated by Django 3.1.7 on 2021-04-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20210404_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='des',
            new_name='des_cate',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_cate',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='status_cate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='des',
            new_name='des_pro',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_pro',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_pro',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_pro',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='status_pro',
        ),
    ]
