# Generated by Django 3.1.7 on 2021-03-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
