# Generated by Django 3.1.7 on 2021-04-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_shippingaddress_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_orderd',
            new_name='date_orderd_order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='status_order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_added',
            new_name='date_added_orderitem',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='quantity_orderitem',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='address_ship',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='date_added',
            new_name='date_added_ship',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phone',
            new_name='phone_ship',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='status',
            new_name='status_ship',
        ),
    ]
