# Generated by Django 3.1.7 on 2021-04-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_auto_20210405_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_orderitem',
            field=models.IntegerField(default=0),
        ),
    ]
